services:
  python-poo: # Serviço para rodar um contêiner Python com Programação Orientada a Objetos
    container_name: python-poo # Nome do contêiner
    image: python:3.12 # Imagem do Docker com Python versão 3.12
    working_dir: /src # Diretório de trabalho dentro do contêiner
    volumes:
      - ./:/src # Monta o diretório atual no diretório de trabalho do contêiner
    command: tail -f /dev/null # Mantém o contêiner em execução, aguardando comandos
